// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKby0VA6EXoJgYEuDX-wVy1NaIFl_3cJI',
    appId: '1:789048285815:web:08af0a26838becc85f8472',
    messagingSenderId: '789048285815',
    projectId: 'flutterauthapp-ac1fb',
    authDomain: 'flutterauthapp-ac1fb.firebaseapp.com',
    storageBucket: 'flutterauthapp-ac1fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9hHeSTR_ccj5ZvB8hgrfzjna-VXVnW8',
    appId: '1:789048285815:android:fc7b84219a09d3c25f8472',
    messagingSenderId: '789048285815',
    projectId: 'flutterauthapp-ac1fb',
    storageBucket: 'flutterauthapp-ac1fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnkonY6Etelq2ecmtA56vV-cdDTMbvVs',
    appId: '1:789048285815:ios:edb86c86dc8cc1615f8472',
    messagingSenderId: '789048285815',
    projectId: 'flutterauthapp-ac1fb',
    storageBucket: 'flutterauthapp-ac1fb.appspot.com',
    iosBundleId: 'com.example.flutterauthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjnkonY6Etelq2ecmtA56vV-cdDTMbvVs',
    appId: '1:789048285815:ios:771edfc55447a3eb5f8472',
    messagingSenderId: '789048285815',
    projectId: 'flutterauthapp-ac1fb',
    storageBucket: 'flutterauthapp-ac1fb.appspot.com',
    iosBundleId: 'com.example.flutterauthapp.RunnerTests',
  );
}
